language: ruby
rvm:
  - 2.1.0
  - jruby-19mode
  - rbx
  - ruby-head
  - jruby-head
  - ree

before_install:
  - uname -a
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - ./script/spec
