language: ruby
rvm:
  - 2.1.0

before_install:
  - uname -a
  - "export USE_SAUCE=true"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

addons:
  sauce_connect:
    secure: "UXCAeVTPhC401SL4EPTcqY7i6BFFhPs59/q0YH1JkN4qIP/6EUe40HXAikgupbeJ9sUGKiLFWVeRahw1rIOv2qySUeVJHulJMnlISjhqLNZur7D7qrzVNP/ehjf5dFEefSBR4xlxcdyP/p24/aYeni6E9LQpRRqLXNESJ1D7ANI="
    secure: "d2Fxpsr8fsNLuLClmqPyTL3vva+aHJFmK34BAQJzLcIvwbqAcOOLWjljvC9/Vb1jvtnAoeTu+9WCSognM5XdFKPLsKAcSKBPuLuisVhUQLoJ30l0pRlR6cqI3jJqCX4ZKvoDmjxNeU2wGh4pl3TtcyD0otV5Kr/Hu32zmGDZMks="

script:
  - ./script/spec
