#!/bin/sh -xe

# Install packages.
bundle --quiet --binstubs

DUMMY_APP_PATH="spec/dummy"

# Prep dummy app db
pushd "$DUMMY_APP_PATH"
  rake db:drop db:setup
  rake db:test:load
popd

rm -rf coverage

# Enable to check spec coverage - only 'elses' should be uncovered
export CHECK_SPEC_COVERAGE=${CHECK_SPEC_COVERAGE:-false}

COVERAGE_GROUP="unit-tests" bin/rake "spec:unit"
COVERAGE_GROUP="firefox-features" BROWSER=firefox bin/rake "spec:features"
COVERAGE_GROUP="chrome-features" BROWSER=chrome bin/rake "spec:features"
bin/rake "spec:quality"
